// Import FontAwesome icons
import {
  faFacebook,
  faGoogle,
  faInstagram,
  faLinkedin,
  faTwitter,
  faYoutube,
  faStripe,
  faSnapchat,
  faWhatsapp,
  faTiktok,
  faDiscord,
  faGithub,
  faPinterest,
  faSpotify,
  faYelp,
  faReact,
  faJs,
  faFigma,
  faHtml5,
  faCss3,
  faGit,
  faPython,
  faNodeJs,
  faAws,
  faXTwitter,
} from "@fortawesome/free-brands-svg-icons";

import {
  faAddressCard,
  faArrowRight,
  faBars,
  faBlog,
  faBurger,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faDumbbell,
  faEnvelope,
  faHandFist,
  faHandshake,
  faHeart,
  faHouse,
  faPaperPlane,
  faPlus,
  faPlusCircle,
  faRightFromBracket,
  faRightToBracket,
  faTrophy,
  faUserMinus,
  faUserPlus,
  faUsers,
  faWrench,
  faXmark,
  faXmarkCircle,
  faXmarkSquare,
  faCaretDown,
  faCaretUp,
  faDollarSign,
  faLock,
  faMagnifyingGlass,
  faUtensils,
  faClipboard,
  faTrash,
  faInbox,
  faReply,
  faShare,
  faUnlock,
  faLockOpen,
  faEye,
  faClock,
  faSmile,
  faPerson,
  faEarth,
  faChartPie,
  faUser,
  faMessage,
  faPhone,
  faCalendar,
  faMinus,
  faMinusCircle,
  faMedal,
  faUserLock,
  faCog,
  faClipboardCheck,
  faUserShield,
  faShoppingCart,
  faQuoteLeft,
  faQuestionCircle,
  faCogs,
  faImage,
  faBook,
  faImages,
  faShareAlt,
  faCreditCard,
  faHashtag,
  faLink,
  faCalculator,
  faGlobe,
  faQuoteRight,
  faChevronDown,
  faChevronUp,
  faHome,
  faCertificate,
  faQuestion,
  faStar,
  faVideo,
  faSearch,
  faArrowLeft,
  faHeading,
  faInfo,
  faPuzzlePiece,
  faDeleteLeft,
  faAnchor,
  faFileText,
  faFileAlt,
  faComment,
  faBullhorn,
  faFire,
  faNotesMedical,
  faBullseye,
  faExclamationTriangle,
  faChartLine,
  faKey,
  faAppleAlt,
  faBrain,
  faArrowUp,
  faComputerMouse,
  faSort,
  faUpload,
  faCopy,
  faSync,
  faParagraph,
  faList,
  faScaleBalanced,
  faWeight,
  faPercent,
  faBalanceScale,
  faRuler,
  faBowlFood,
  faCow,
  faEdit,
  faStairs,
  faRepeat,
  faClose,
  faSave,
  faLightbulb,
  faPowerOff,
  faBirthdayCake,
  faT,
  faHeader,
  faFlag,
  faDashboard,
  faFile,
  faBox,
  faCampground,
  faBone,
  faCode,
  faBriefcase,
  faSchool,
  faChevronRight,
  faArrowAltCircleDown,
} from "@fortawesome/free-solid-svg-icons";

// Organize and categorize FontAwesome icons for easy reference
const faPresetIcons = {
  // Brand Icons
  yelp: faYelp,
  twitter: faTwitter,
  facebook: faFacebook,
  youtube: faYoutube,
  stripe: faStripe,
  google: faGoogle,
  linkedIn: faLinkedin,
  instagram: faInstagram,
  snapchat: faSnapchat,
  whatsapp: faWhatsapp,
  tiktok: faTiktok,
  discord: faDiscord,
  github: faGithub,
  pinterest: faPinterest,
  spotify: faSpotify,

  // Auth Icons
  signUp: faUsers,
  signIn: faRightToBracket,
  signOut: faRightFromBracket,

  // Solid Icons
  xMark: faXmark,
  xMarkCircle: faXmarkCircle,
  plus: faPlus,
  plusCircle: faPlusCircle,
  check: faCheck,
  checkCircle: faCheckCircle,
  envelope: faEnvelope,
  house: faHouse,
  bars: faBars,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  arrowUp: faArrowUp,
  heart: faHeart,
  paperPlane: faPaperPlane,
  addressCard: faAddressCard,
  blog: faBlog,
  burger: faBurger,
  dumbbell: faDumbbell,
  wrench: faWrench,
  handFist: faHandFist,
  handshake: faHandshake,
  users: faUsers,
  userPlus: faUserPlus,
  userMinus: faUserMinus,
  trophy: faTrophy,
  checkSquare: faCheckSquare,
  xMarkSquare: faXmarkSquare,
  caretDown: faCaretDown,
  caretUp: faCaretUp,
  dollarSign: faDollarSign,
  lock: faLock,
  utensils: faUtensils,
  clipboard: faClipboard,
  trash: faTrash,
  magnifyingGlass: faMagnifyingGlass,
  inbox: faInbox,
  message: faMessage,
  reply: faReply,
  share: faShare,
  unlock: faUnlock,
  lockOpen: faLockOpen,
  eye: faEye,
  clock: faClock,
  smile: faSmile,
  person: faPerson,
  earth: faEarth,
  pieChart: faChartPie,
  user: faUser,
  phone: faPhone,
  calendar: faCalendar,
  minus: faMinus,
  minusCircle: faMinusCircle,
  medal: faMedal,
  userLock: faUserLock,
  cog: faCog,
  clipboardCheck: faClipboardCheck,
  userShield: faUserShield,
  shoppingCart: faShoppingCart,
  quoteLeft: faQuoteLeft,
  quoteRight: faQuoteRight,
  questionCircle: faQuestionCircle,
  cogs: faCogs,
  image: faImage,
  images: faImages,
  book: faBook,
  shareAlt: faShareAlt,
  creditCard: faCreditCard,
  hashtag: faHashtag,
  link: faLink,
  calculator: faCalculator,
  globe: faGlobe,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronRight: faChevronRight,
  home: faHome,
  certificate: faCertificate,
  question: faQuestion,
  star: faStar,
  video: faVideo,
  search: faSearch,
  heading: faHeading,
  info: faInfo,
  puzzlePiece: faPuzzlePiece,
  deleteLeft: faDeleteLeft,
  anchor: faAnchor,
  fileText: faFileText,
  file: faFileAlt,
  comment: faComment,
  bullhorn: faBullhorn,
  fire: faFire,
  notesMedical: faNotesMedical,
  bullseye: faBullseye,
  exclamationTriangle: faExclamationTriangle,
  chartLine: faChartLine,
  key: faKey,
  appleAlt: faAppleAlt,
  brain: faBrain,
  scrollWheel: faComputerMouse,
  sort: faSort,
  upload: faUpload,
  copy: faCopy,
  sync: faSync,
  paragraph: faParagraph,
  list: faList,
  scaleBalanced: faScaleBalanced,
  weight: faWeight,
  percent: faPercent,
  balanceScale: faBalanceScale,
  ruler: faRuler,
  bowlFood: faBowlFood,
  cow: faCow,
  edit: faEdit,
  stairs: faStairs,
  repeat: faRepeat,
  close: faClose,
  save: faSave,
  lightBulb: faLightbulb,
  powerOff: faPowerOff,
  birthdayCake: faBirthdayCake,
  title: faT,
  subtitle: faParagraph,
  description: faInfo,
  features: faList,
  markdown: faFileText,
  content: faFileText,
  week: faCalendar,
  answer: faReply,
  header: faHeader,
  flag: faFlag,
  bone: faBone,
  arrowAltCircleDown: faArrowAltCircleDown,
  dashboard: faDashboard,
  box: faBox,
  campground: faCampground,
};

// Define types for the preset icons for better type checking
type FaPresetIconsTypes = keyof typeof faPresetIcons;

const headerPrimaryLinks = [
  {
    title: "Home",
    href: "/",
    description: "Welcome to my portfolio",
    faIconUrl: faHouse,
  },
  {
    title: "About",
    href: "#about",
    description: "Learn more about me and my background",
    faIconUrl: faUser,
    dropdownLinks: [
      {
        title: "Experience",
        href: "#experience",
        description: "My professional work history",
        faIconUrl: faBriefcase,
      },
      {
        title: "Education",
        href: "#education",
        description: "My academic qualifications",
        faIconUrl: faSchool,
      },
      {
        title: "Certifications",
        href: "#certifications",
        description: "Professional certifications I've earned",
        faIconUrl: faCertificate,
      },
      {
        title: "Resume",
        href: "/resume",
        description: "Download my full resume",
        faIconUrl: faFile,
      },
    ],
  },
  {
    title: "Skills",
    href: "#skills",
    description: "Technical skills and expertise",
    faIconUrl: faCode,
  },
  // {
  //   title: "Blog",
  //   href: "/blog",
  //   description: "My thoughts and insights on tech",
  //   faIconUrl: faBlog,
  // },
  {
    title: "Portfolio",
    href: "#portfolio",
    description: "Showcase of my projects and work",
    faIconUrl: faBriefcase,
  },
  {
    title: "Services",
    href: "#services",
    description: "Professional services I offer",
    faIconUrl: faWrench,
  },
  {
    title: "Contact",
    href: "#contact",
    description: "Get in touch with me",
    faIconUrl: faEnvelope,
    dropdownLinks: [
      {
        title: "Email",
        href: "mailto:olivermorla3@gmail.com",
        description: "Send me an email",
        faIconUrl: faEnvelope,
      },
    ],
  },
];

type HeaderPrimaryLinksTypes = typeof headerPrimaryLinks;
type HeaderDropdownLinksTypes = (typeof headerPrimaryLinks)[0]["dropdownLinks"];

const footerPrimaryLinks = [
  {
    title: "Navigation",
    links: [
      { title: "Home", href: "/" },
      { title: "About", href: "#about" },
      { title: "Skills", href: "#skills" },
      { title: "Portfolio", href: "#portfolio" },
      { title: "Services", href: "#services" },
      { title: "Blog", href: "/blog" },
      { title: "Contact", href: "#contact" },
    ],
  },
  {
    title: "Resources",
    links: [
      { title: "Resume", href: "#resume" },
      { title: "Certifications", href: "#certifications" },
      { title: "Case Studies", href: "/case-studies" },
      { title: "Testimonials", href: "#testimonials" },
    ],
  },
  {
    title: "Legal",
    links: [
      { title: "Privacy Policy", href: "/privacy-policy" },
      { title: "Terms of Service", href: "/terms-of-service" },
    ],
  },
  {
    title: "Connect",
    links: [
      {
        title: "LinkedIn",
        href: "https://www.linkedin.com/in/oliver-morla/",
      },
      { title: "GitHub", href: "https://github.com/OliverMorla" },
      { title: "Twitter", href: "https://twitter.com/OliverMorlaX" },
      { title: "Email", href: "mailto:olivermorla3@gmail.com" },
    ],
  },
];

const socialMediaLinks = [
  {
    title: "GitHub",
    href: "https://github.com/OliverMorla",
    iconUrl: faGithub,
  },
  {
    title: "LinkedIn",
    href: "https://www.linkedin.com/in/oliver-morla/",
    iconUrl: faLinkedin,
  },
  {
    title: "Twitter",
    href: "https://twitter.com/OliverMorlaX",
    iconUrl: faXTwitter,
  },
  {
    title: "Email",
    href: "mailto:olivermorla3@gmail.com",
    iconUrl: faEnvelope,
  },
];

// Page content
const listOfServices = [
  {
    title: "Web Development",
    faIconUrl: faReact,
    price: "$200 - $1800",
    description:
      "Expert web developer who specializes in building and maintaining high-quality websites and web-based applications.",
    libraries: [
      "React.js",
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "Node.js",
      "Express",
      "MongoDB",
      "PostgreSQL",
      "AWS",
      "Docker",
    ],
    features: [
      "Custom website design and development",
      "Responsive design for all devices",
      "Integration of third-party services",
      "Database management and optimization",
      "Security enhancements",
      "Performance optimization",
      "Regular updates and maintenance",
    ],
  },
  {
    title: "Mobile Development",
    faIconUrl: faJs,
    price: "$600 - $2400",
    description:
      "Experienced application developer who specializes in creating custom software solutions for businesses.",
    libraries: [
      "React Native",
      "Expo",
      "Node.js",
      "Express",
      "MongoDB",
      "PostgreSQL",
      "AWS",
      "Docker",
    ],
    features: [
      "Custom mobile app development",
      "API integration",
      "Database management",
      "Security enhancements",
      "Performance optimization",
      "Regular updates and maintenance",
    ],
  },
  {
    title: "Software Development",
    faIconUrl: faCode,
    price: "$400 - $2000",
    libraries: [
      "Electron.js",
      "Python",
      "Django",
      "SQL",
      "Tableau",
      "AWS",
      "Docker",
    ],
    description:
      "Custom tailored software solutions for businesses and organizations.",
    features: [
      "Custom software development",
      "API integration",
      "Database management",
      "Security enhancements",
      "Performance optimization",
      "Regular updates and maintenance",
    ],
  },
];

const experienceHistory = [
  {
    companyName: "Gambit Dev LLC",
    location: "Long Island City, NY",
    position: "Full Stack Developer",
    startDate: "Feb 2023",
    endDate: "Current",
    responsibilities: [
      "Pioneered the use of TypeScript in web application development, achieving a 30% reduction in code maintenance efforts.",
      "Revolutionized user interface creation with custom React UI Components, boosting user retention by 25% across platforms.",
      "Optimized data management using MongoDB and Prisma, improving database performance by 25%.",
      "Boosted application performance and scalability by 50% and 30%, respectively, via strategic integration of AWS cloud services.",
      "Cut operational expenses by 20% by implementing AWS Lambda and API Gateway for serverless architecture.",
      "Employed Redux for state management in React apps, streamlining state handling and reducing debugging time by 30%.",
      "Decreased deployment issues by 25% using Docker for consistent environments across development, testing, and production.",
      "Increased customer satisfaction by 20% and accessibility compliance by 30% through collaboration on React-based interfaces.",
      "Integrated AI models, leveraging LLM expertise to enhance application capabilities by 35%, improving user interaction.",
    ],
  },
  {
    companyName: "New Yorkers International",
    location: "Queens, NY",
    position: "Full Stack Engineer",
    startDate: "May 2020",
    endDate: "Jan 2023",
    responsibilities: [
      "Increased user engagement by 40% through React, TypeScript, and Next.js, enhancing UI/UX and overall performance.",
      "Reduced server response times by 50% and improved reliability by 30% with a microservices architecture transition.",
      "Managed backend services using Node.js/Express and Django, achieving a 50% increase in application processing speed.",
      "Constructed robust testing frameworks with Jest and Selenium, reducing software anomalies by 35% post-launch.",
      "Delivered over 10 significant product enhancements, collaborating with diverse teams.",
      "Automated complex workflows using Python, saving the team 20 hours monthly in manual tasks.",
      "Orchestrated AWS RDS instances for PostgreSQL, ensuring 99.99% uptime and robust data replication and backup solutions.",
      "Advocated for code quality and team growth through mentorship and regular code reviews.",
      "Built cross-platform mobile apps with React Native, contributing to a 25% increase in mobile user engagement.",
    ],
  },
  {
    companyName: "New Yorkers International",
    location: "Queens, NY",
    position: "SW Engineering Intern",
    startDate: "Oct 2019",
    endDate: "Apr 2020",
    responsibilities: [
      "Boosted system efficiency by 25% through comprehensive software testing and optimization.",
      "Refined SQL queries in collaboration with database specialists, achieving a 30% increase in database throughput.",
      "Formulated innovative data processing algorithms, improving the accuracy and speed of Tableau report generation.",
      "Facilitated the completion of 7 critical projects with key insights in data analysis and software evaluation.",
      "Recommended and executed system enhancements, contributing to three significant software updates.",
      "Streamlined operational processes, assisting in the development of system improvements.",
    ],
  },
];

const certifications = [
  {
    title: "IBM Full Stack Software Developer Professional Certificate",
    certs: [
      "Introduction to Cloud Computing",
      "Introduction to Web Development with HTML, CSS, JavaScript",
      "Introduction to Containers w/Docker, Kubernetes & OpenShift",
      "Getting Started with Git and GitHub",
      "Developing Front-End Apps with React",
      "Developing Back-End Apps with Node.js and Express",
      "Developing AI Applications with Python and Flask",
      "Application Development Using Microservices and Serverless",
      "Python for Data Science, AI, & Development",
      "Django Application Development with SQL and Databases",
      "Generative AI: Introduction",
    ],
    institution: "IBM",
  },
  {
    title: "AWS Certified Developer – Associate",
    institution: "AWS",
    status: "In Progress",
  },
];

const achievements = [
  {
    description: "Application Performance Optimization",
    impact:
      "Improved application performance by 25%, increasing user capacity through critical code refactoring and optimization.",
  },
  {
    description: "Team Leadership and Project Delivery",
    impact:
      "Led a team of 8 developers, delivering 15 feature-rich releases on time, achieving 95% stakeholder satisfaction.",
  },
  {
    description: "Cloud Infrastructure Migration",
    impact:
      "Reduced operational costs by 20% and enhanced scalability by migrating legacy systems to AWS cloud infrastructure.",
  },
  {
    description: "Full-Stack Feature Development",
    impact:
      "Boosted annual revenue by 30% by designing full-stack features with React, Node.js, and MongoDB.",
  },
  {
    description: "Team Productivity Enhancement",
    impact:
      "Enhanced team productivity by 35% and shortened onboarding time through mentoring and training junior developers.",
  },
  {
    description: "Scalability Solution Implementation",
    impact:
      "Solved a scalability issue, improving system resilience and increasing traffic handling capacity by 40% with microservices.",
  },
  {
    description: "Data-Driven Decision Making",
    impact:
      "Developed a custom analytics dashboard, increasing marketing ROI by 20% with real-time data visualization insights.",
  },
];

const education = [
  {
    institution: "New York City College of Technology (NYCCT)",
    degree: "Bachelor of Technology in Computer Systems Technology",
    graduationYear: 2023,
    faIconUrl: faSchool,
  },
];

const skillsIcons = [
  {
    title: "React",
    progress: "95%",
    fontAwesomeIconUrl: faReact,
  },
  {
    title: "JavaScript",
    progress: "95%",
    fontAwesomeIconUrl: faJs,
  },
  {
    title: "HTML5",
    progress: "95%",
    fontAwesomeIconUrl: faHtml5,
  },
  {
    title: "CSS3",
    progress: "95%",
    fontAwesomeIconUrl: faCss3,
  },
  {
    title: "Github",
    progress: "95%",
    fontAwesomeIconUrl: faGithub,
  },
  {
    title: "Git",
    progress: "95%",
    fontAwesomeIconUrl: faGit,
  },
  {
    title: "Python",
    progress: "95%",
    fontAwesomeIconUrl: faPython,
  },
  {
    title: "Node.js",
    progress: "95%",
    fontAwesomeIconUrl: faNodeJs,
  },
  {
    title: "AWS Lambda & API Gateway",
    progress: "95%",
    fontAwesomeIconUrl: faAws,
  },
  {
    title: "Figma",
    progress: "95%",
    fontAwesomeIconUrl: faFigma,
  },
];

const projects = [
  {
    title: "Portfolio",
    category: "Portfolio",
    demoUrl: "https://www.olivermorla.com/",
    imageUrl: "/assets/images/portfolio/olivermorla.webp",
    sourceCodeUrl: null,
    description:
      "My personal portfolio website built with Next.js, Tailwind CSS, and TypeScript.",
  },
  {
    title: "Mind Body Shift",
    category: "Health & Wellness",
    demoUrl: "https://www.mindbodyshift.net/",
    imageUrl: "/assets/images/portfolio/mindbodyshift.webp",
    sourceCodeUrl: null,
    description:
      "Transform your lifestyle with Mind Body Shift's personalized coaching, MBS Portal, and courses on nutrition, exercise mastery, and mental health.",
  },
  {
    title: "Johnny Luna",
    category: "Portfolio",
    demoUrl: "https://www.johnnyluna.com/",
    imageUrl: "/assets/images/portfolio/johnnyluna.webp",
    sourceCodeUrl: null,
    description:
      "Portfolio website for Johnny Luna built with Next.js, Tailwind CSS, and TypeScript.",
  },
  {
    title: "Gambit Dev",
    category: "Gaming & eSports",
    demoUrl: "https://www.gambit.dev/",
    imageUrl: "/assets/images/portfolio/gambitdev.webp",
    sourceCodeUrl: null,
    description:
      "Here at Gambit Dev, we strive to deliver the best, innovate where others have not, and to create a fun and enjoyable workplace for our employees and clients.",
  },
  {
    title: "Elemental Roofing Solutions",
    category: "Business & Finance",
    demoUrl: "https://www.elementalroofsolutions.com/",
    imageUrl: "/assets/images/portfolio/elementalroofsolutions.webp",
    sourceCodeUrl: null,
    description:
      "Elemental is more than a roofing company. As a family-owned business rooted in integrity and craftsmanship, we bring over two decades of expertise to every project.",
  },
  {
    title: "Around Your Way Fitness",
    category: "Health & Wellness",
    demoUrl: "https://www.aroundyourwayfitness.com/",
    imageUrl: "/assets/images/portfolio/aroundyourwayfitness.webp",
    sourceCodeUrl: null,
    description:
      "A comprehensive fitness platform tailored for a personal trainer to deliver accessible fitness services.",
  },
  {
    title: "Crunch Fitness - Utilities",
    category: "Business & Finance",
    demoUrl: "https://www.crunchfitness.app/",
    imageUrl: "/assets/images/portfolio/crunch-utilities.webp",
    sourceCodeUrl: null,
    description:
      "Crunch Fitness Utilities is a suite of tools designed to streamline operations and enhance the customer experience at Crunch Fitness.",
  },
  {
    title: "Bed.gg",
    category: "Gaming & eSports",
    demoUrl: "https://bed.gg/",
    imageUrl: "/assets/images/portfolio/bedgg.webp",
    sourceCodeUrl: null,
    description: "Experience Competitive Minecraft like never before",
  },
  {
    title: "Quip.gg",
    category: "Gaming & eSports",
    demoUrl: "https://quip.gg/",
    imageUrl: "/assets/images/portfolio/quipgg.webp",
    description: "Crypto e-sports. Real money gaming. Competitive Experience.",
    sourceCodeUrl: null,
  },
  {
    title: "Rohan Hossain",
    category: "Portfolio",
    demoUrl: "https://www.rohanhossain.com/",
    imageUrl: "/assets/images/portfolio/rohanhossain.webp",
    sourceCodeUrl: null,
    description:
      "A personal portfolio website designed to showcase skills, experiences, and projects of a data engineer and developer.",
  },
  {
    title: "Tasmiah Chowdhury",
    category: "Portfolio",
    demoUrl: "https://tasmiahch.com/",
    imageUrl: "/assets/images/portfolio/tasmiahch.webp",
    sourceCodeUrl: null,
    description:
      "A professional real estate portfolio platform designed to elevate the personal brand and services of a licensed realtor in New York City.",
  },
  // {
  //   title: "New Yorkers International",
  //   category: "Business & Finance",
  //   demoUrl: "https://www.newyorkersinternational.com/",
  //   // imageUrl: "/assets/portfolio/new-yorkers-international.webp",
  //   imageUrl: null,
  //   sourceCodeUrl: null,
  //   description: "",
  // },
  // {
  //   title: "MyFitnessClient",
  //   category: "Health & Wellness",
  //   demoUrl: "https://myfitnessclient.com/",
  //   // imageUrl: "/assets/portfolio/my-fitness-client.webp",
  //   imageUrl: null,
  //   sourceCodeUrl: null,
  //   description: "",
  // },
  // {
  //   title: "Consensus.fund",
  //   category: "Business & Finance",
  //   demoUrl: "https://www.consensus.fund/",
  //   // imageUrl: "/assets/portfolio/consensus-fund.webp",
  //   imageUrl: null,
  //   sourceCodeUrl: null,
  //   description: "",
  // },
];

const personalProjects = [
  {
    title: "Hollister Clone",
    description:
      "Devised a high-caliber, responsive e-commerce platform mirroring Hollister, utilizing ReactJS, NextJS, TypeScript, and Framer-Motion, delivering an exceptional UI/UX.",
    imageUrl: "/assets/portfolio/hollisterclone.webp",
    category: "E-commerce",
    demoUrl: "https://hollister-clone.vercel.app/",
    sourceCodeUrl: "https://github.com/OliverMorla/hollister-clone",
  },
  {
    title: "Threads Clone",
    imageUrl: "/assets/portfolio/threads-clone-login.webp",
    description:
      'Developed a dynamic social media platform, "Threads-Clone," using a MERN stack, incorporating MongoDB, NextJS 14 with server actions, React, and Tailwind CSS, showcasing state-of-the-art web development practices.',
    category: "Social Media",
    sourceCodeUrl: "https://github.com/OliverMorla/threads-clone",
    demoUrl: "https://threads-clone-two-amber.vercel.app/",
  },
  {
    title: "NextBlogs",
    description:
      "A blog website built with Next.js, Tailwind CSS, and TypeScript.",
    imageUrl: "/assets/portfolio/nextblogs.webp",
    category: "Blog",
    demoUrl: "https://nextblogs-olivermorla.vercel.app/",
    sourceCodeUrl: "https://github.com/OliverMorla/nextblogs",
  },
  {
    title: "PyNotes",
    description:
      "A note-taking application built with Python, Django, and SQLite.",
    imageUrl: "/assets/portfolio/pynotes.webp",
    category: "Blog",
    demoUrl: "https://github.com/OliverMorla/pynotes",
    sourceCodeUrl: "https://github.com/OliverMorla/pynotes",
  },
  {
    title: "Job Finder",
    description:
      "A job finding application built with React native and Firebase.",
    imageUrl: "/assets/portfolio/job-finder.webp",
    category: "Job Finder",
    demoUrl: "https://github.com/OliverMorla/job-finder",
    sourceCodeUrl: "https://github.com/OliverMorla/job-finder",
  },
];

export {
  headerPrimaryLinks,
  footerPrimaryLinks,
  socialMediaLinks,
  faPresetIcons,

  // Content
  listOfServices,
  experienceHistory,
  achievements,
  certifications,
  education,
  skillsIcons,
  projects,
  personalProjects,
};

export type {
  FaPresetIconsTypes,
  HeaderPrimaryLinksTypes,
  HeaderDropdownLinksTypes,
};
