// Import FontAwesome icons
import {
  faFacebook,
  faGoogle,
  faInstagram,
  faLinkedin,
  faTwitter,
  faYoutube,
  faStripe,
  faSnapchat,
  faWhatsapp,
  faTiktok,
  faDiscord,
  faGithub,
  faPinterest,
  faSpotify,
  faYelp,
  faReact,
  faJs,
  faFigma,
  faHtml5,
  faCss3,
  faGit,
  faPython,
  faNodeJs,
  faAws,
} from "@fortawesome/free-brands-svg-icons";

import {
  faArrowAltCircleDown,
  faAddressCard,
  faArrowRight,
  faBars,
  faBlog,
  faBurger,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faDumbbell,
  faEnvelope,
  faHandFist,
  faHandshake,
  faHeart,
  faHouse,
  faPaperPlane,
  faPlus,
  faPlusCircle,
  faRightFromBracket,
  faRightToBracket,
  faTrophy,
  faUserMinus,
  faUserPlus,
  faUsers,
  faWrench,
  faXmark,
  faXmarkCircle,
  faXmarkSquare,
  faCaretDown,
  faCaretUp,
  faDollarSign,
  faLock,
  faMagnifyingGlass,
  faUtensils,
  faClipboard,
  faTrash,
  faInbox,
  faReply,
  faShare,
  faUnlock,
  faLockOpen,
  faEye,
  faClock,
  faSmile,
  faPerson,
  faEarth,
  faChartPie,
  faUser,
  faMessage,
  faPhone,
  faCalendar,
  faMinus,
  faMinusCircle,
  faMedal,
  faUserLock,
  faCog,
  faClipboardCheck,
  faUserShield,
  faShoppingCart,
  faQuoteLeft,
  faQuestionCircle,
  faCogs,
  faImage,
  faBook,
  faImages,
  faShareAlt,
  faCreditCard,
  faHashtag,
  faLink,
  faCalculator,
  faGlobe,
  faQuoteRight,
  faChevronDown,
  faChevronUp,
  faHome,
  faCertificate,
  faQuestion,
  faStar,
  faVideo,
  faSearch,
  faArrowLeft,
  faHeading,
  faInfo,
  faPuzzlePiece,
  faDeleteLeft,
  faAnchor,
  faFileText,
  faFileAlt,
  faComment,
  faBullhorn,
  faFire,
  faNotesMedical,
  faBullseye,
  faExclamationTriangle,
  faChartLine,
  faKey,
  faAppleAlt,
  faBrain,
  faArrowUp,
  faComputerMouse,
  faSort,
  faUpload,
  faCopy,
  faSync,
  faParagraph,
  faList,
  faScaleBalanced,
  faWeight,
  faPercent,
  faBalanceScale,
  faRuler,
  faBowlFood,
  faCow,
  faEdit,
  faStairs,
  faRepeat,
  faClose,
  faSave,
  faLightbulb,
  faPowerOff,
  faBirthdayCake,
  faT,
  faHeader,
  faFlag,
  faDashboard,
  faFile,
  faBox,
  faCampground,
  faBone,
  faCode,
  faBriefcase,
  faSchool,
  faChevronRight,
} from "@fortawesome/free-solid-svg-icons";

// Organize and categorize FontAwesome icons for easy reference
const faPresetIcons = {
  // Brand Icons
  yelp: faYelp,
  twitter: faTwitter,
  facebook: faFacebook,
  youtube: faYoutube,
  stripe: faStripe,
  google: faGoogle,
  linkedIn: faLinkedin,
  instagram: faInstagram,
  snapchat: faSnapchat,
  whatsapp: faWhatsapp,
  tiktok: faTiktok,
  discord: faDiscord,
  github: faGithub,
  pinterest: faPinterest,
  spotify: faSpotify,

  // Auth Icons
  signUp: faUsers,
  signIn: faRightToBracket,
  signOut: faRightFromBracket,

  // Solid Icons
  xMark: faXmark,
  xMarkCircle: faXmarkCircle,
  plus: faPlus,
  plusCircle: faPlusCircle,
  check: faCheck,
  checkCircle: faCheckCircle,
  envelope: faEnvelope,
  house: faHouse,
  bars: faBars,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  arrowUp: faArrowUp,
  heart: faHeart,
  paperPlane: faPaperPlane,
  addressCard: faAddressCard,
  blog: faBlog,
  burger: faBurger,
  dumbbell: faDumbbell,
  wrench: faWrench,
  handFist: faHandFist,
  handshake: faHandshake,
  users: faUsers,
  userPlus: faUserPlus,
  userMinus: faUserMinus,
  trophy: faTrophy,
  checkSquare: faCheckSquare,
  xMarkSquare: faXmarkSquare,
  caretDown: faCaretDown,
  caretUp: faCaretUp,
  dollarSign: faDollarSign,
  lock: faLock,
  utensils: faUtensils,
  clipboard: faClipboard,
  trash: faTrash,
  magnifyingGlass: faMagnifyingGlass,
  inbox: faInbox,
  message: faMessage,
  reply: faReply,
  share: faShare,
  unlock: faUnlock,
  lockOpen: faLockOpen,
  eye: faEye,
  clock: faClock,
  smile: faSmile,
  person: faPerson,
  earth: faEarth,
  pieChart: faChartPie,
  user: faUser,
  phone: faPhone,
  calendar: faCalendar,
  minus: faMinus,
  minusCircle: faMinusCircle,
  medal: faMedal,
  userLock: faUserLock,
  cog: faCog,
  clipboardCheck: faClipboardCheck,
  userShield: faUserShield,
  shoppingCart: faShoppingCart,
  quoteLeft: faQuoteLeft,
  quoteRight: faQuoteRight,
  questionCircle: faQuestionCircle,
  cogs: faCogs,
  image: faImage,
  images: faImages,
  book: faBook,
  shareAlt: faShareAlt,
  creditCard: faCreditCard,
  hashtag: faHashtag,
  link: faLink,
  calculator: faCalculator,
  globe: faGlobe,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronRight: faChevronRight,
  home: faHome,
  certificate: faCertificate,
  question: faQuestion,
  star: faStar,
  video: faVideo,
  search: faSearch,
  heading: faHeading,
  info: faInfo,
  puzzlePiece: faPuzzlePiece,
  deleteLeft: faDeleteLeft,
  anchor: faAnchor,
  fileText: faFileText,
  file: faFileAlt,
  comment: faComment,
  bullhorn: faBullhorn,
  fire: faFire,
  notesMedical: faNotesMedical,
  bullseye: faBullseye,
  exclamationTriangle: faExclamationTriangle,
  chartLine: faChartLine,
  key: faKey,
  appleAlt: faAppleAlt,
  brain: faBrain,
  scrollWheel: faComputerMouse,
  sort: faSort,
  upload: faUpload,
  copy: faCopy,
  sync: faSync,
  paragraph: faParagraph,
  list: faList,
  scaleBalanced: faScaleBalanced,
  weight: faWeight,
  percent: faPercent,
  balanceScale: faBalanceScale,
  ruler: faRuler,
  bowlFood: faBowlFood,
  cow: faCow,
  edit: faEdit,
  stairs: faStairs,
  repeat: faRepeat,
  close: faClose,
  save: faSave,
  lightBulb: faLightbulb,
  powerOff: faPowerOff,
  birthdayCake: faBirthdayCake,
  title: faT,
  subtitle: faParagraph,
  description: faInfo,
  features: faList,
  markdown: faFileText,
  content: faFileText,
  week: faCalendar,
  answer: faReply,
  header: faHeader,
  flag: faFlag,
  bone: faBone,
};

// Define types for the preset icons for better type checking
type FaPresetIconsTypes = keyof typeof faPresetIcons;

const headerPrimaryLinks = [
  {
    title: "Home",
    href: "/",
    description: "Welcome to my portfolio",
    faIconUrl: faHouse,
  },
  {
    title: "About",
    href: "#about",
    description: "Learn more about me and my background",
    faIconUrl: faUser,
    dropdownLinks: [
      {
        title: "Experience",
        href: "#experience",
        description: "My professional work history",
        faIconUrl: faBriefcase,
      },
      {
        title: "Education",
        href: "#education",
        description: "My academic qualifications",
        faIconUrl: faSchool,
      },
      {
        title: "Certifications",
        href: "#certifications",
        description: "Professional certifications I've earned",
        faIconUrl: faCertificate,
      },
      {
        title: "Resume",
        href: "#resume",
        description: "Download my full resume",
        faIconUrl: faFile,
      },
    ],
  },
  {
    title: "Skills",
    href: "#skills",
    description: "Technical skills and expertise",
    faIconUrl: faCode,
  },
  {
    title: "Blog",
    href: "/blog",
    description: "My thoughts and insights on tech",
    faIconUrl: faBlog,
  },
  {
    title: "Portfolio",
    href: "#portfolio",
    description: "Showcase of my projects and work",
    faIconUrl: faBriefcase,
  },
  {
    title: "Services",
    href: "#services",
    description: "Professional services I offer",
    faIconUrl: faWrench,
  },
  {
    title: "Contact",
    href: "#contact",
    description: "Get in touch with me",
    faIconUrl: faEnvelope,
    dropdownLinks: [
      {
        title: "Email",
        href: "mailto:olivermorla3@gmail.com",
        description: "Send me an email",
        faIconUrl: faEnvelope,
      },
    ],
  },
];

const footerPrimaryLinks = [
  {
    title: "Navigation",
    links: [
      { title: "Home", href: "/" },
      { title: "About", href: "#about" },
      { title: "Skills", href: "#skills" },
      { title: "Portfolio", href: "#portfolio" },
      { title: "Services", href: "#services" },
      { title: "Blog", href: "/blog" },
      { title: "Contact", href: "#contact" },
    ],
  },
  {
    title: "Resources",
    links: [
      { title: "Resume", href: "#resume" },
      { title: "Certifications", href: "#certifications" },
      { title: "Case Studies", href: "/case-studies" },
      { title: "Testimonials", href: "#testimonials" },
    ],
  },
  {
    title: "Legal",
    links: [
      { title: "Privacy Policy", href: "/privacy-policy" },
      { title: "Terms of Service", href: "/terms-of-service" },
      { title: "Cookie Policy", href: "/cookie-policy" },
    ],
  },
  {
    title: "Connect",
    links: [
      {
        title: "LinkedIn",
        href: "https://www.linkedin.com/in/oliver-morla/",
      },
      { title: "GitHub", href: "https://github.com/OliverMorla" },
      { title: "Twitter", href: "https://twitter.com/OliverMorla" },
      { title: "Email", href: "mailto:your.email@example.com" },
    ],
  },
];

const socialMediaLinks = [
  {
    title: "GitHub",
    href: "https://github.com/OliverMorla",
    iconUrl: faGithub,
  },
  {
    title: "LinkedIn",
    href: "https://www.linkedin.com/in/oliver-morla/",
    iconUrl: faLinkedin,
  },
  {
    title: "Twitter",
    href: "https://twitter.com/OliverMorla",
    iconUrl: faTwitter,
  },
  {
    title: "Email",
    href: "mailto:olivermorla3@gmail.com",
    iconUrl: faEnvelope,
  },
];

// Page content
const listOfServices = [
  {
    title: "Web Development",
    fontAwesomeIconUrl: faReact,
    description:
      "Expert web developer who specializes in building and maintaining high-quality websites and web-based applications.",
  },
  {
    title: "App Development",
    fontAwesomeIconUrl: faJs,
    description:
      "Experienced application developer who specializes in creating custom software solutions for businesses.",
  },
  {
    title: "UI/UX Design",
    fontAwesomeIconUrl: faFigma,
    description:
      "Creative UI/UX designer who specializes in creating unique and engaging user experiences for digital products.",
  },
];

const experienceHistory = [
  {
    companyName: "Gambit Dev LLC",
    location: "Long Island City, NY",
    position: "Full Stack Developer",
    startDate: "Feb 2023",
    endDate: "Current",
    responsibilities: [
      "Pioneered the use of TypeScript in web application development, achieving a 30% reduction in code maintenance efforts.",
      "Revolutionized user interface creation with React, boosting user retention by 25% across platforms.",
      "Optimized data management using MongoDB and Mongoose, improving database performance by 25%.",
      "Boosted application performance and scalability by 50% and 30%, respectively, via strategic integration of AWS cloud services.",
      "Cut operational expenses by 20% by implementing AWS Lambda and API Gateway for serverless architecture.",
      "Employed Redux for state management in React apps, streamlining state handling and reducing debugging time by 30%.",
      "Applied Docker for containerization of React/Node.js applications, ensuring consistency across development, testing, and production environments and reducing deployment issues by 25%.",
      "Collaborated with design teams to create React-based interfaces, improving customer satisfaction by 20% and compliance with accessibility standards by 30%.",
    ],
  },
  {
    companyName: "SR Tech",
    location: "Queens, NY",
    position: "Full Stack Engineer",
    startDate: "May 2020",
    endDate: "Jan 2023",
    responsibilities: [
      "Developed high-impact web applications using React, TypeScript, and Next.js, which improved user engagement by 40% due to superior UI/UX designs.",
      "Drove the transition to a microservices architecture, halving server response times, enhancing reliability by 30%, and significantly boosting system scalability and maintainability.",
      "Managed backend services using Node.js/Express and Django, achieving a 50% increase in application processing speed.",
      "Constructed robust testing frameworks with Jest and Selenium, reducing software anomalies by 35% post-launch.",
      "Delivered over 10 significant product enhancements, collaborating effectively with diverse teams.",
      "Automated complex workflows using Python, saving the team 20 hours monthly in manual tasks.",
      "Orchestrated AWS RDS instances for PostgreSQL, ensuring 99.99% uptime and robust data replication and backup solutions.",
      "Advocated for code quality and team growth through mentorship and regular code reviews.",
      "Built cross-platform mobile apps with React Native, contributing to a 25% increase in mobile user engagement.",
    ],
  },
  {
    companyName: "SR Tech",
    location: "Queens, NY",
    position: "Software Engineering Intern",
    startDate: "Oct 2019",
    endDate: "Apr 2020",
    responsibilities: [
      "Boosted system efficiency by 25% through comprehensive software testing and optimization.",
      "Refined SQL queries in collaboration with database specialists, achieving a 30% increase in database throughput.",
      "Formulated innovative data processing algorithms, improving the accuracy and speed of Tableau report generation.",
      "Facilitated the completion of 7 critical projects with key insights in data analysis and software evaluation.",
      "Recommended and executed system enhancements, contributing to three significant software updates.",
      "Streamlined operational processes, assisting in the development of system improvements.",
    ],
  },
];

const certifications = [
  {
    title: "IBM Full Stack Software Developer Professional Certificate",
    certs: [
      "Introduction to Cloud Computing",
      "Introduction to Web Development with HTML, CSS, JavaScript",
      "Introduction to Containers w/Docker, Kubernetes & OpenShift",
      "Getting Started with Git and GitHub",
      "Developing Front-End Apps with React",
      "Developing Back-End Apps with Node.js and Express",
      "Python for Data Science, AI, & Development",
      "Django Application Development with SQL and Databases",
    ],
    institution: "IBM",
  },
  {
    title: "AWS Certified Developer – Associate",
    status: "In Progress",
  },
];

const achievements = [
  {
    description: "Optimized Application Performance",
    impact:
      "Increased existing application performance by refactoring critical code sections, resulting in a 25% increase in concurrent user capacity.",
  },
  {
    description: "Led Cross-Functional Teams",
    impact:
      "Led a team of 8 developers and collaborated with UX/UI designers and product managers to deliver over 15 feature-rich releases on schedule, maintaining a 95% satisfaction rating from stakeholders.",
  },
  {
    description: "Cloud Infrastructure Optimization",
    impact:
      "Successfully migrated legacy systems to AWS, achieving a 20% reduction in operational costs and significant improvements in scalability and reliability.",
  },
  {
    description: "Crafted Full-Stack Features",
    impact:
      "Played a key role in designing and implementing full-stack features using React, Node.js, and MongoDB, contributing to a 30% increase in annual revenue for a flagship product.",
  },
  {
    description: "Mentored and Trained Junior Developers",
    impact:
      "Heightened team productivity by 35% and significantly reduced onboarding time for new team members by mentoring and training junior developers.",
  },
  {
    description: "Innovative Problem-Solving",
    impact:
      "Solved a critical scalability issue by implementing a microservices architecture, improving system resilience, and facilitating a 40% increase in traffic handling capacity.",
  },
  {
    description: "Data-Driven Decision Making",
    impact:
      "Developed a custom analytics dashboard with real-time data visualization, enabling data-driven decision-making and contributing to a 20% increase in marketing ROI.",
  },
];

const education = [
  {
    institution: "New York City College of Technology (NYCCT)",
    degree: "Bachelor of Technology in Computer Systems Technology",
    graduationYear: "Already Graduated",
    fontAwesomeIconUrl: faSchool,
  },
];

const skillsIcons = [
  {
    title: "React",
    progress: "95%",
    fontAwesomeIconUrl: faReact,
  },
  {
    title: "JavaScript",
    progress: "95%",
    fontAwesomeIconUrl: faJs,
  },
  {
    title: "HTML5",
    progress: "95%",
    fontAwesomeIconUrl: faHtml5,
  },
  {
    title: "CSS3",
    progress: "95%",
    fontAwesomeIconUrl: faCss3,
  },
  {
    title: "Github",
    progress: "95%",
    fontAwesomeIconUrl: faGithub,
  },
  {
    title: "Git",
    progress: "95%",
    fontAwesomeIconUrl: faGit,
  },
  {
    title: "Python",
    progress: "95%",
    fontAwesomeIconUrl: faPython,
  },
  {
    title: "Node.js",
    progress: "95%",
    fontAwesomeIconUrl: faNodeJs,
  },
  {
    title: "AWS Lambda & API Gateway",
    progress: "95%",
    fontAwesomeIconUrl: faAws,
  },
  {
    title: "Figma",
    progress: "95%",
    fontAwesomeIconUrl: faFigma,
  },
];

const portfolioImages = [
  {
    imageUrl: "/assets/portfolio/portfolio.webp",
    title: "Portfolio",
    description: "",
    projectType: "Portfolio",
    sourceCodeUrl: "https://github.com/OliverMorla/olivermorla.github.io",
    demoUrl: "https://www.olivermorla.com/",
  },
  {
    imageUrl: "/assets/portfolio/hollister-clone.webp",
    title: "Hollister Clone",
    description:
      "Devised a high-caliber, responsive e-commerce platform mirroring Hollister, utilizing ReactJS, NextJS, TypeScript, and Framer-Motion, delivering an exceptional UI/UX.",
    projectType: "E-commerce",
    sourceCodeUrl: "https://github.com/OliverMorla/hollister-clone",
    demoUrl: "https://hollister-clone.vercel.app/",
  },
  {
    imageUrl: "/assets/portfolio/threads-clone-login.webp",
    title: "Threads Clone",
    description:
      'Developed a dynamic social media platform, "Threads-Clone," using a MERN stack, incorporating MongoDB, NextJS 14 with server actions, React, and Tailwind CSS, showcasing state-of-the-art web development practices.',
    projectType: "Social Media",
    sourceCodeUrl: "https://github.com/OliverMorla/threads-clone",
    demoUrl: "https://threads-clone-two-amber.vercel.app/",
  },
];

export {
  headerPrimaryLinks,
  footerPrimaryLinks,
  socialMediaLinks,
  faPresetIcons,

  // Content
  listOfServices,
  experienceHistory,
  achievements,
  certifications,
  education,
  skillsIcons,
  portfolioImages,
};

export type { FaPresetIconsTypes };
