import type { CollectionConfig } from "payload";

export const Certifications: CollectionConfig = {
  slug: "certifications",
  fields: [
    {
      name: "title",
      type: "text",
      required: true,
    },
    {
      name: "issuer",
      type: "select",
      options: [
        "AWS",
        "Google",
        "Microsoft",
        "IBM",
        "Oracle",
        "SAP",
        "Salesforce",
        "Cisco",
        "VMware",
        "Dell",
        "HP",
        "Lenovo",
        "Tata",
        "Wipro",
        "HCL",
        "Tech Mahindra",
        "Capgemini",
        "Accenture",
        "TCS",
        "Infosys",
        "Coursera",
        "Udemy",
        "LinkedIn",
        "Other",
      ],
    },
    {
      name: "subtitle",
      type: "text",
    },
    {
      name: "description",
      type: "textarea",
      admin: {
        rows: 5,
      },
    },
    {
      name: "company",
      type: "select",
      options: [
        "AWS",
        "Google",
        "Microsoft",
        "IBM",
        "Oracle",
        "SAP",
        "Salesforce",
        "Cisco",
        "VMware",
        "Dell",
        "HP",
        "Lenovo",
        "Tata",
        "Wipro",
        "HCL",
        "Tech Mahindra",
        "Capgemini",
        "Accenture",
        "TCS",
        "Infosys",
        "Udemy",
        "LinkedIn",
        "Other",
      ],
    },
    {
      name: "issuedDate",
      type: "date",
    },
    {
      name: "expiresAt",
      type: "date",
    },
  ],
};
